#!/bin/sh
export CCACHE_MAXSIZE=10G
export CCACHE_CPP2=true
export CCACHE_HARDLINK=true
export CCACHE_SLOPPINESS=file_macro,time_macros,include_file_mtime,include_file_ctime,file_stat_matches

if type -p /usr/local/bin/ccache >/dev/null 2>&1; then
    exec /usr/local/bin/ccache clang "$@"
elif type -p /opt/homebrew/bin/ccache >/dev/null 2>&1; then
    exec /opt/homebrew/bin/ccache clang "$@"
else
    exec clang "$@"
fi

